function S = shearing_matrix(c, rovina)

%Vytvoøení transformaèní matice pro zkosení
%-----------------------------------------------------
%Ve 3D zobrazení je 6 možných smìrù zkosení:
% 'xy' shear X by Y
% 'xz' shear X by Z 
% 'yx' shear Y by X
% 'yz' shear Y by Z
% 'zx' shear Z by X
% 'zy' shear Z by Y
%------------------------------------------------------
%
%Napøíklad:
%Zkosení s faktorem 0.8 ve smìru osy x, rizene osou y.
%S = shearing_matrix(0.8,'xy')

% (c) 2009 Bartoò
% (c) 2010-2012 drobné úpravy Rajmic

%%
if strcmp(rovina,'xy')
    S = [1 c 0 0;...
         0 1 0 0;...
         0 0 1 0;...
         0 0 0 1];
elseif strcmp(rovina,'yx')
     S = [1 0 0 0;...
          c 1 0 0;...
          0 0 1 0;...
          0 0 0 1];
elseif strcmp(rovina,'xz')
     S = [1 0 c 0;...
          0 1 0 0;...
          0 0 1 0;...
          0 0 0 1];
elseif strcmp(rovina,'zx')
     S = [1 0 0 0;...
          0 1 0 0;...
          c 0 1 0;...
          0 0 0 1];
elseif strcmp(rovina,'zy')
     S = [1 0 0 0;...
          0 1 0 0;...
          0 c 1 0;...
          0 0 0 1];
elseif strcmp(rovina,'yz')
     S = [1 0 0 0;...
          0 1 c 0;...
          0 0 1 0;...
          0 0 0 1];
else
    error('Zadejte správnì rovinu zkosení!');
end